feat: Update package and example
surfstudio/flutter-push-notification pull request #41
Opened 2024-04-05 10:39 UTC by Evgenia-bit

## Checklist

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Is there an existing issue for this PR?
  - _link issue here_ (use keywords like `fix`, `close`, `resolve` etc. if necessary)
- [x] Have the files been linted and formatted?
- [x] Have the docs been updated to match the changes in the PR?
- [x] Have the tests been updated to match the changes in the PR?
- [x] Attached videos/screenshots demonstrating the fix/feature.
- [x] Have you run the tests locally to confirm they pass?

## New Features

### What new capabilities does this PR add?

- `_getStrategyBuilder` in `PushHandleStrategyFactory` now processes `messageData` the same on both ios and android
- `enum MessageHandlerType` has been updated to reflect the changed message handlers in FirebaseMessaging. `onLaunch` and `onResume` removed, `onBackgroundMessage` and `onMessageOpenedApp` added.
- fixed parsing error in the `internalOnSelectNotification` method in `NotificationController`
- `handleMessage` in `PushHandler` method has been updated to match the updated `MessageHandlerType`
- fixed the problem of incorrect display of push notifications on iOS
-  improved example
- updated docs: no longer need to specify `click_action: FLUTTER_NOTIFICATION_CLICK` in notification and add `intent-filter` to android manifest
- updated tests

Android:

https://github.com/surfstudio/flutter-push-notification/assets/63193897/cbdf6a9c-b7cd-46a4-b315-9a8d963516c4

IOS:

https://github.com/surfstudio/flutter-push-notification/assets/63193897/6ee5d04e-9650-4175-b259-d623316ddf3d

2024-04-09 08:56 UTC, ekinsdrow requested changes

2024-04-09 08:56 UTC, ekinsdrow commented on example/android/app/build.gradle
> +        targetSdkVersion 30
Why 30? Why not 34, like `compileSdkVersion`?

2024-04-09 08:56 UTC, ekinsdrow commented on example/bundled-service-worker/firebase-messaging-sw.ts
> +const app = initializeApp({
I am not sure, but maybe it would be best to remove all api keys and firebase data like data in this repository at all cause every one can just use it and it's not so cool and potentially can cost some money to us

But i am not sure, if you have another opinion let me now

2024-04-09 08:56 UTC, ekinsdrow commented on example/lib/domain/message.dart
> +      int.parse(data['extraInt'].toString()),
```dart
int.tryParse(data['extraInt'].toString()) ?? 0,
double.tryParse(data['extraDouble'].toString()) ?? 0,
```

2024-04-09 08:56 UTC, ekinsdrow commented on example/lib/firebase_options.dart
> +class DefaultFirebaseOptions {
Maybe better to remove creds

2024-04-10 13:59 UTC, Evgenia-bit commented on example/android/app/build.gradle
> +        targetSdkVersion 30
If set 34, the application crashes after sending a notification with this error:
![image](https://github.com/surfstudio/flutter-push-notification/assets/63193897/83f2ce36-0301-447a-a163-6b288ddf5de0)

2024-04-10 16:16 UTC, ekinsdrow commented on README.md
> +## Overview
Dublicate

2024-04-12 07:42 UTC, ekinsdrow approved these changes

2024-04-12 07:43 UTC, merged